name: Development testing

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Local Build
      run: |
        pip install -e .[dev]
    - name: Unit Tests
      run: |
      pytest -m "not legacy"
